const topSkills = [
  { title: 'Algorithms' },
  { title: 'Analytical Skills' },
  { title: 'Big Data' },
  { title: 'Calculating' },
  { title: 'Compiling Statistics' },
  { title: 'Data Analytics' },
  { title: 'Data Mining' },
  { title: 'Database Design' },
  { title: 'Database Management' },
  { title: 'Documentation' },
  { title: 'Modeling' },
  { title: 'Modification' },
  { title: 'Needs Analysis' },
  { title: 'Quantitative Research' },
  { title: 'Quantitative Reports' },
  { title: 'Statistical Analysis' },
  { title: 'Applications' },
  { title: 'Configuration' },
  { title: 'Debugging' },
  { title: 'Development' },
  { title: 'Design' },
  { title: 'Hardware' },
  { title: 'Information Technology' },
  { title: 'Network Architecture' },
  { title: 'Networking' },
  { title: 'Operating Systems' },
  { title: 'Security' },
  { title: 'Servers' },
  { title: 'Software' },
  { title: 'Storage' },
  { title: 'Technical Support' },
  { title: 'Testing' },
  { title: 'Tools' },
  { title: 'Systems Analysis' },
  { title: 'Troubleshooting' },
  { title: 'Usability' },
  { title: 'Engineering' },
  { title: 'Performance Review' },
  { title: 'Programming' },
  { title: 'Project Planning' },
  { title: 'Quality Control' },
  { title: 'Task Management' },
  { title: 'Blogging' },
  { title: 'Digital Media' },
  { title: 'Social Media Platforms' },
  { title: 'Web Analytics' },
  { title: 'Research' },
  { title: 'Technical Documentation' },
  { title: 'Facebook' },
  { title: 'Facebook' },
];

export default topSkills;
